#!/bin/sh
interpreter="$(dirname "$0")/.build/rvk/ethereum-kompiled/interpreter"
assembled="$(mktemp)"
kast="$(mktemp)"
output="$(mktemp)"
kast_output="$(mktemp)"
trap "rm -rf $kast $output $kast_output $assembled" INT TERM EXIT
"$(dirname "$0")/assemble-iele-test" "$1" > "$assembled"
"$(dirname "$0")/kast-json.py" "$assembled" > "$kast"
$interpreter "$(dirname "$0")/.build/rvk/ethereum-kompiled/realdef.cma" -c PGM "$kast" textfile -c SCHEDULE '`DEFAULT_IELE`(.KList)' text -c MODE '`NORMAL_IELE`(.KList)' text --output-file "$output"
exit=$?
if [ $exit -eq 0 ]; then
  exit 0
fi
k-bin-to-text "$output" "$kast_output"
cat "$kast_output"
printf "\n"
exit $exit
