#!/bin/sh
interpreter="$(dirname "$0")/.build/standalone/iele-testing-kompiled/interpreter"
assembled="$(mktemp)"
kast="$(mktemp)"
output="$(mktemp)"
kast_output="$(mktemp)"
trap "rm -rf $kast $output $kast_output $assembled" INT TERM EXIT
"$(dirname "$0")/assemble-iele-test" "$1" > "$assembled" || exit $?
"$(dirname "$0")/kast-json.py" "$assembled" > "$kast"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
shift 1
$interpreter "$(dirname "$0")/.build/standalone/iele-testing-kompiled/realdef.cma" -c PGM "$kast" textfile -c SCHEDULE '`DEFAULT_IELE-GAS`(.KList)' text -c MODE '`NORMAL`(.KList)' text --output-file "$output" "$@"
exit=$?
if [ $exit -eq 0 ]; then
  exit 0
fi
"$(dirname "$0")"/tests/ci/rv-k/k-distribution/target/release/k/bin/k-bin-to-text "$output" "$kast_output"
cat "$kast_output"
printf "\n"
exit $exit
