#!/bin/sh
interpreter="$(dirname "$0")/.build/check/well-formedness-kompiled/interpreter"
kast="$(mktemp)"
trap "rm -rf $kast" INT TERM EXIT
krun --parser "kast -d $(dirname "$0")/.build/check -s Contract" -cSCHEDULE=DANSE --output none -d "$(dirname "$0")/.build/check" "$@"
exit=$?
if [ $exit -eq 0 ]; then
  exit 0
fi
printf "error: IELE contract failed to pass well-formedness check.\n"
exit $exit
