#!/usr/bin/env bash

set -euo pipefail

notif() { echo "== $@" >&2 ; }
fatal() { echo "[FATAL] $@" ; exit 1 ; }

INSTALL_BIN="$(dirname $0)"
INSTALL_LIB=${INSTALL_BIN}/../lib/kiele

export PATH="$INSTALL_BIN:$INSTALL_LIB:$PATH"
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:-}:/usr/local/lib

check_k_install() {
    type -p kore-exec &> /dev/null \
        || fatal "Must have K installed! See https://github.com/kframework/k/releases."
    type -p kast &> /dev/null \
        || fatal "Must have K installed! See https://github.com/kframework/k/releases."
    type -p krun &> /dev/null \
        || fatal "Must have K installed! See https://github.com/kframework/k/releases."
}

make_temp_trap() {
    local tmpdesc tmpfile
    tmpdesc="$1" ; shift
    tmpfile="$(mktemp)"
    if $debug; then
        notif "$tmpdesc: $tmpfile"
    else
        trap "rm -rf $tmpfile" INT TERM EXIT
    fi
    echo "$tmpfile"
}

# Runners
# -------

### Does not depend on K Install

run_assemble() {
    iele-assemble "$run_file" "$@"
}

run_interpret() {
    local kast output status
    kast=$(make_temp_trap kast)
    output=$(make_temp_trap output)
    status=0
    kore-json.py "$run_file" "$cschedule" "$cmode" > "$kast"
    case "$backend" in
        standalone)
            interpret_cmd=(iele-interpreter "$kast" "$depth" "$output" "$@")
            if $debug; then
                gdb --args "${interpret_cmd[@]}"
            else
                "${interpret_cmd[@]}" || status="$?"
            fi
            ;;
        haskell)
            check_k_install
            kore_cmd=(kore-exec "$backend_dir/$definition-kompiled/definition.kore" --pattern "$kast" --module "$module" --output "$output")
            [[ "$depth" == "-1" ]] || kore_cmd+=(--depth "$depth")
            kore_cmd+=("$@")
            "${kore_cmd[@]}" || status="$?"
            ;;
        *)
            fatal "Unknown backend: $backend"
            ;;
    esac
    if $unparse || [[ "$status" != '0' ]]; then
        kprint "$backend_dir/$definition-kompiled" "$output"
        printf "\n"
        exit "$status"
    fi
}

run_krun_internal() {
    check_k_install
    krun --directory "$backend_dir" -cSCHEDULE="$cschedule" -pSCHEDULE='cat' --depth "$depth" "$run_file" "$@"
}

run_krun() {
    run_krun_internal -cMODE="$cmode" -pMODE='cat' "$@"
}

run_check() {
    local kore
    kore=$(make_temp_trap kore)
    kast --directory "$backend_dir" -s Contract --output kore "$run_file" > $kore
    run_file="$kore"
    run_krun_internal --parser cat --output none "$@"
}

run_vm() {
    exec iele-vm "$kiele_port" "$kiele_host"
}

# Main
# ----

run_command="$1" ; shift

if [[ "$run_command" == 'help' ]] || [[ "$run_command" == '--help' ]] ; then
    echo "
        usage: $0 assemble                                                              <pgm> <assemble arg>*
               $0 interpret    [--backend (standalone|haskell)]            <KIELE arg>* <pgm> <interpret arg>*
               $0 krun         [--backend (standalone|haskell|node|check)] <KIELE arg>* <pgm> <K arg>*
               $0 check                                                    <KIELE arg>* <pgm> <K arg>*
               $0 vm                                                       <KIELE arg>*

               $0 [help|--help|version|--version]

           $0 assemble  : Translate IELE assembly <pgm to IELE bytecode
           $0 interpret : Run given input JSON or IELE <pgm>
           $0 krun      : Run given input <pgm> using 'krun'
           $0 check     : Run the IELE well-formedness checker on <pgm>
           $0 vm        : Run the KIELE VM server.

           $0 help    : Display this help message.
           $0 version : Display the versions of KIELE in use.

           Note: <pgm> is a path to a file containing a IELE program/test (possible in JSON format)
                 <assemble arg> is an argument to the assembler
                 <interpret arg> is an argument you want to pass to the interpreter
                 <K arg> is an argument you want to pass to K
                 <KIELE arg> is one of (--no-unparse|--debug|--host|--port|--mode|--schedule|--module|--definition|--depth)
    "
    exit 0
fi

if [[ "$run_command" == 'version' ]] || [[ "$run_command" == '--version' ]] ; then
    notif "KIELE Version"
    cat $INSTALL_LIB/version
    exit 0
fi

backend='standalone'
[[ "$run_command" != 'check' ]] || backend='check'
debug=false
unparse=true
mode='NORMAL'
schedule='DEFAULT'
kiele_port='8545'
kiele_host='127.0.0.1'
module='IELE-TESTING'
definition='iele-testing'
depth=-1
args=()
while [[ $# -gt 0 ]]; do
    arg="$1"
    case $arg in
        --backend)    backend="$2"    ; shift 2 ;;
        --debug)      debug=true      ; shift   ;;
        --no-unparse) unparse=false   ; shift   ;;
        --mode)       mode="$2"       ; shift 2 ;;
        --module)     module="$2"     ; shift 2 ;;
        --definition) definition="$2" ; shift 2 ;;
        --schedule)   schedule="$2"   ; shift 2 ;;
        --depth)      depth=$2        ; shift 2 ;;
        -p|--port)    kiele_port="$2" ; shift 2 ;;
        -h|--host)    kiele_host="$2" ; shift 2 ;;
        *)            args+=("$1")    ; shift   ;;
    esac
done
if [[ "${#args[@]}" -gt 0 ]]; then
  set -- "${args[@]}"
fi

! $debug || set -x

backend_dir="${backend_dir:-$INSTALL_LIB/$backend}"

cmode='Lbl'$mode'{}()'
cschedule='Lbl'$schedule'{}()'

if [[ "$run_command" != 'vm' ]]; then
    run_file="$1" ; shift
    [[ -f "$run_file" ]] || [[ "$run_file" == '-' ]] || fatal "File does not exist: $run_file"
fi

case "$run_command" in
    assemble)  run_assemble  "$@" ;;
    interpret) run_interpret "$@" ;;
    krun)      run_krun      "$@" ;;
    check)     run_check     "$@" ;;
    vm)        run_vm        "$@" ;;
    *) $0 help ; fatal "Unknown command: $run_command" ;;
esac
