#!/bin/sh

PGM=$1

assembled="$(mktemp)"
kast="$(mktemp)"
output="$(mktemp)"
trap "rm -rf $kast $output $assembled" INT TERM EXIT
"$(dirname "$0")/assemble-iele-test" "$PGM" > "$assembled" || exit $?
"$(dirname "$0")/kore-json.py" "$assembled" '`DEFAULT`(.KList)' '`VMTESTS`(.KList)' > "$kast"

kore-exec .build/haskell/iele-testing-kompiled/definition.kore --pattern "$kast" --module IELE-TESTING --smt none --output "$output"

exit=$?
if [ $exit -eq 0 ]; then
  exit 0
fi
kprint "$(dirname "$interpreter")" "$output"
printf "\n"
exit $exit
