#!/bin/sh
assembled="$(mktemp)"
kast="$(mktemp)"
output="$(mktemp)"
trap "rm -rf $kast $output $assembled" INT TERM EXIT
"$(dirname "$0")/assemble-iele-test" "$1" > "$assembled" || exit $?
"$(dirname "$0")/kore-json.py" "$assembled" '`DEFAULT`(.KList)' '`VMTESTS`(.KList)' > "$kast"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
shift 1
iele-interpreter "$kast" -1 "$output" "$@"
exit=$?
if [ $exit -eq 0 ]; then
  exit 0
fi
kprint "$(dirname "$interpreter")" "$output"
printf "\n"
exit $exit
