ARG BASE_IMAGE=ubuntu:bionic
FROM ${BASE_IMAGE}
ARG BASE_IMAGE

ENV TZ=America/Chicago
RUN    ln --symbolic --no-dereference --force /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone

RUN    apt-get update         \
    && apt-get upgrade --yes  \
    && apt-get install --yes  \
            curl              \
            git               \
            sudo

ARG USER_ID=1000
ARG GROUP_ID=1000
RUN    groupadd -g $GROUP_ID user                                                \
    && useradd --create-home --uid $USER_ID --shell /bin/sh --gid $GROUP_ID user \
    && echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER user:user

ENV LANG=C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive
