ARG BASE_IMAGE=ubuntu:bionic
FROM ${BASE_IMAGE}
ARG BASE_IMAGE

ENV TZ=America/Chicago
RUN    ln --symbolic --no-dereference --force /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone

RUN    apt-get update         \
    && apt-get upgrade --yes  \
    && apt-get install --yes  \
            autoconf          \
            curl              \
            git               \
            libgmp-dev        \
            make              \
            pkg-config        \
            python            \
            opam              \
            sudo              \
            zlib1g-dev

ARG USER_ID=1000
ARG GROUP_ID=1000
RUN    groupadd -g $GROUP_ID user                                                \
    && useradd --create-home --uid $USER_ID --shell /bin/sh --gid $GROUP_ID user \
    && echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER user:user

RUN    opam init --yes --disable-sandboxing                                  \
    && opam install --yes zarith hex uuidm rlp yojson cryptokit ocaml-protoc

ENV LANG=C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive
