name: "Release"
on:
  release:
    types:
      - created

jobs:
  nix-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Nix
        uses: cachix/install-nix-action@v15
        with:
          install_url: https://releases.nixos.org/nix/nix-2.7.0/install

      - name: Upload release.nix
        uses: ttuegel/upload-release.nix@v1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
